insert into person(name, year_of_birthday, month_of_birthday, day_of_birthday) values ('martin', 1991, 8, 15)
insert into person(name, year_of_birthday, month_of_birthday, day_of_birthday) values ('david', 1992, 7, 21)
insert into person(name, year_of_birthday, month_of_birthday, day_of_birthday) values ('dennis', 1993, 10, 15)
insert into person(name, year_of_birthday, month_of_birthday, day_of_birthday) values ('sophia', 1994, 8, 31)
insert into person(name, year_of_birthday, month_of_birthday, day_of_birthday) values ('benny', 1995, 12, 23)
insert into person(name, year_of_birthday, month_of_birthday, day_of_birthday, job, hobby, phone_number, address) values ('tony', 1991, 7, 10, 'officer', 'reading', '010-1111-1112', '서울')
insert into person(name, deleted) values ('andrew', true)
